// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.1
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployPhase int32

const (
	DeployPhase_DEPLOY_PHASE_UNSPECIFIED DeployPhase = 0
	DeployPhase_DEPLOY_PHASE_PENDING     DeployPhase = 1
	DeployPhase_DEPLOY_PHASE_PULLING     DeployPhase = 2
	DeployPhase_DEPLOY_PHASE_CREATING    DeployPhase = 3
	DeployPhase_DEPLOY_PHASE_RUNNING     DeployPhase = 4
	DeployPhase_DEPLOY_PHASE_FAILED      DeployPhase = 5
)

// Enum value maps for DeployPhase.
var (
	DeployPhase_name = map[int32]string{
		0: "DEPLOY_PHASE_UNSPECIFIED",
		1: "DEPLOY_PHASE_PENDING",
		2: "DEPLOY_PHASE_PULLING",
		3: "DEPLOY_PHASE_CREATING",
		4: "DEPLOY_PHASE_RUNNING",
		5: "DEPLOY_PHASE_FAILED",
	}
	DeployPhase_value = map[string]int32{
		"DEPLOY_PHASE_UNSPECIFIED": 0,
		"DEPLOY_PHASE_PENDING":     1,
		"DEPLOY_PHASE_PULLING":     2,
		"DEPLOY_PHASE_CREATING":    3,
		"DEPLOY_PHASE_RUNNING":     4,
		"DEPLOY_PHASE_FAILED":      5,
	}
)

func (x DeployPhase) Enum() *DeployPhase {
	p := new(DeployPhase)
	*p = x
	return p
}

func (x DeployPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (DeployPhase) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[0]
}

func (x DeployPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployPhase.Descriptor instead.
func (DeployPhase) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EnrollRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type EnrollResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AgentCredential string                 `protobuf:"bytes,2,opt,name=agent_credential,json=agentCredential,proto3" json:"agent_credential,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *EnrollResponse) GetAgentCredential() string {
	if x != nil {
		return x.AgentCredential
	}
	return ""
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_DeployStatus
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetDeployStatus() *DeployStatus {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_DeployStatus); ok {
			return x.DeployStatus
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_DeployStatus struct {
	DeployStatus *DeployStatus `protobuf:"bytes,2,opt,name=deploy_status,json=deployStatus,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_DeployStatus) isAgentMessage_Payload() {}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_DeployStack
	//	*ControlMessage_Ack
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetDeployStack() *DeployStackCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_DeployStack); ok {
			return x.DeployStack
		}
	}
	return nil
}

func (x *ControlMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_DeployStack struct {
	DeployStack *DeployStackCommand `protobuf:"bytes,1,opt,name=deploy_stack,json=deployStack,proto3,oneof"`
}

type ControlMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*ControlMessage_DeployStack) isControlMessage_Payload() {}

func (*ControlMessage_Ack) isControlMessage_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Resources     *ResourceSnapshot      `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	Containers    []*ContainerSummary    `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Heartbeat) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Heartbeat) GetResources() *ResourceSnapshot {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Heartbeat) GetContainers() []*ContainerSummary {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ResourceSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,2,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	DiskPercent   float64                `protobuf:"fixed64,3,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSnapshot) Reset() {
	*x = ResourceSnapshot{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSnapshot) ProtoMessage() {}

func (x *ResourceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSnapshot.ProtoReflect.Descriptor instead.
func (*ResourceSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceSnapshot) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceSnapshot) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *ResourceSnapshot) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

type ContainerSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,4,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSummary) Reset() {
	*x = ContainerSummary{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSummary) ProtoMessage() {}

func (x *ContainerSummary) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSummary.ProtoReflect.Descriptor instead.
func (*ContainerSummary) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerSummary) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type DeployStackCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	StackName     string                 `protobuf:"bytes,2,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	ComposeYaml   string                 `protobuf:"bytes,3,opt,name=compose_yaml,json=composeYaml,proto3" json:"compose_yaml,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployStackCommand) Reset() {
	*x = DeployStackCommand{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployStackCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployStackCommand) ProtoMessage() {}

func (x *DeployStackCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployStackCommand.ProtoReflect.Descriptor instead.
func (*DeployStackCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DeployStackCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployStackCommand) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *DeployStackCommand) GetComposeYaml() string {
	if x != nil {
		return x.ComposeYaml
	}
	return ""
}

func (x *DeployStackCommand) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type DeployStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Phase         DeployPhase            `protobuf:"varint,2,opt,name=phase,proto3,enum=agent.v1.DeployPhase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployStatus) Reset() {
	*x = DeployStatus{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployStatus) ProtoMessage() {}

func (x *DeployStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployStatus.ProtoReflect.Descriptor instead.
func (*DeployStatus) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DeployStatus) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployStatus) GetPhase() DeployPhase {
	if x != nil {
		return x.Phase
	}
	return DeployPhase_DEPLOY_PHASE_UNSPECIFIED
}

func (x *DeployStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeployStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Ack) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\"X\n" +
	"\x0eEnrollResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12)\n" +
	"\x10agent_credential\x18\x02 \x01(\tR\x0fagentCredential\"\x8d\x01\n" +
	"\fAgentMessage\x123\n" +
	"\theartbeat\x18\x01 \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\rdeploy_status\x18\x02 \x01(\v2\x16.agent.v1.DeployStatusH\x00R\fdeployStatusB\t\n" +
	"\apayload\"\x81\x01\n" +
	"\x0eControlMessage\x12A\n" +
	"\fdeploy_stack\x18\x01 \x01(\v2\x1c.agent.v1.DeployStackCommandH\x00R\vdeployStack\x12!\n" +
	"\x03ack\x18\x02 \x01(\v2\r.agent.v1.AckH\x00R\x03ackB\t\n" +
	"\apayload\"\xd3\x01\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x128\n" +
	"\tresources\x18\x03 \x01(\v2\x1a.agent.v1.ResourceSnapshotR\tresources\x12:\n" +
	"\n" +
	"containers\x18\x04 \x03(\v2\x1a.agent.v1.ContainerSummaryR\n" +
	"containers\"w\n" +
	"\x10ResourceSnapshot\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x02 \x01(\x01R\n" +
	"memPercent\x12!\n" +
	"\fdisk_percent\x18\x03 \x01(\x01R\vdiskPercent\"q\n" +
	"\x10ContainerSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12#\n" +
	"\rdeployment_id\x18\x04 \x01(\tR\fdeploymentId\"\xec\x01\n" +
	"\x12DeployStackCommand\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18\x02 \x01(\tR\tstackName\x12!\n" +
	"\fcompose_yaml\x18\x03 \x01(\tR\vcomposeYaml\x127\n" +
	"\x03env\x18\x04 \x03(\v2%.agent.v1.DeployStackCommand.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x01\n" +
	"\fDeployStatus\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12+\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x15.agent.v1.DeployPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"$\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId*\xad\x01\n" +
	"\vDeployPhase\x12\x1c\n" +
	"\x18DEPLOY_PHASE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DEPLOY_PHASE_PENDING\x10\x01\x12\x18\n" +
	"\x14DEPLOY_PHASE_PULLING\x10\x02\x12\x19\n" +
	"\x15DEPLOY_PHASE_CREATING\x10\x03\x12\x18\n" +
	"\x14DEPLOY_PHASE_RUNNING\x10\x04\x12\x17\n" +
	"\x13DEPLOY_PHASE_FAILED\x10\x052\x8c\x01\n" +
	"\fAgentSession\x12;\n" +
	"\x06Enroll\x12\x17.agent.v1.EnrollRequest\x1a\x18.agent.v1.EnrollResponse\x12?\n" +
	"\aSession\x12\x16.agent.v1.AgentMessage\x1a\x18.agent.v1.ControlMessage(\x010\x01BGZEgithub.com/ankitapaul1586-cmd/pspocketedge/internal/shared/pb/agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agent_v1_agent_proto_goTypes = []any{
	(DeployPhase)(0),              // 0: agent.v1.DeployPhase
	(*EnrollRequest)(nil),         // 1: agent.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 2: agent.v1.EnrollResponse
	(*AgentMessage)(nil),          // 3: agent.v1.AgentMessage
	(*ControlMessage)(nil),        // 4: agent.v1.ControlMessage
	(*Heartbeat)(nil),             // 5: agent.v1.Heartbeat
	(*ResourceSnapshot)(nil),      // 6: agent.v1.ResourceSnapshot
	(*ContainerSummary)(nil),      // 7: agent.v1.ContainerSummary
	(*DeployStackCommand)(nil),    // 8: agent.v1.DeployStackCommand
	(*DeployStatus)(nil),          // 9: agent.v1.DeployStatus
	(*Ack)(nil),                   // 10: agent.v1.Ack
	nil,                           // 11: agent.v1.DeployStackCommand.EnvEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	5,  // 0: agent.v1.AgentMessage.heartbeat:type_name -> agent.v1.Heartbeat
	9,  // 1: agent.v1.AgentMessage.deploy_status:type_name -> agent.v1.DeployStatus
	8,  // 2: agent.v1.ControlMessage.deploy_stack:type_name -> agent.v1.DeployStackCommand
	10, // 3: agent.v1.ControlMessage.ack:type_name -> agent.v1.Ack
	12, // 4: agent.v1.Heartbeat.sent_at:type_name -> google.protobuf.Timestamp
	6,  // 5: agent.v1.Heartbeat.resources:type_name -> agent.v1.ResourceSnapshot
	7,  // 6: agent.v1.Heartbeat.containers:type_name -> agent.v1.ContainerSummary
	11, // 7: agent.v1.DeployStackCommand.env:type_name -> agent.v1.DeployStackCommand.EnvEntry
	0,  // 8: agent.v1.DeployStatus.phase:type_name -> agent.v1.DeployPhase
	12, // 9: agent.v1.DeployStatus.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 10: agent.v1.AgentSession.Enroll:input_type -> agent.v1.EnrollRequest
	3,  // 11: agent.v1.AgentSession.Session:input_type -> agent.v1.AgentMessage
	2,  // 12: agent.v1.AgentSession.Enroll:output_type -> agent.v1.EnrollResponse
	4,  // 13: agent.v1.AgentSession.Session:output_type -> agent.v1.ControlMessage
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_DeployStatus)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*ControlMessage_DeployStack)(nil),
		(*ControlMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
