// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.1
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployPhase int32

const (
	DeployPhase_DEPLOY_PHASE_UNSPECIFIED DeployPhase = 0
	DeployPhase_DEPLOY_PHASE_PENDING     DeployPhase = 1
	DeployPhase_DEPLOY_PHASE_PULLING     DeployPhase = 2
	DeployPhase_DEPLOY_PHASE_CREATING    DeployPhase = 3
	DeployPhase_DEPLOY_PHASE_RUNNING     DeployPhase = 4
	DeployPhase_DEPLOY_PHASE_FAILED      DeployPhase = 5
)

// Enum value maps for DeployPhase.
var (
	DeployPhase_name = map[int32]string{
		0: "DEPLOY_PHASE_UNSPECIFIED",
		1: "DEPLOY_PHASE_PENDING",
		2: "DEPLOY_PHASE_PULLING",
		3: "DEPLOY_PHASE_CREATING",
		4: "DEPLOY_PHASE_RUNNING",
		5: "DEPLOY_PHASE_FAILED",
	}
	DeployPhase_value = map[string]int32{
		"DEPLOY_PHASE_UNSPECIFIED": 0,
		"DEPLOY_PHASE_PENDING":     1,
		"DEPLOY_PHASE_PULLING":     2,
		"DEPLOY_PHASE_CREATING":    3,
		"DEPLOY_PHASE_RUNNING":     4,
		"DEPLOY_PHASE_FAILED":      5,
	}
)

func (x DeployPhase) Enum() *DeployPhase {
	p := new(DeployPhase)
	*p = x
	return p
}

func (x DeployPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (DeployPhase) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[0]
}

func (x DeployPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployPhase.Descriptor instead.
func (DeployPhase) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type TaskPhase int32

const (
	TaskPhase_TASK_PHASE_UNSPECIFIED TaskPhase = 0
	TaskPhase_TASK_PHASE_RUNNING     TaskPhase = 1
	TaskPhase_TASK_PHASE_COMPLETED   TaskPhase = 2
	TaskPhase_TASK_PHASE_FAILED      TaskPhase = 3
)

// Enum value maps for TaskPhase.
var (
	TaskPhase_name = map[int32]string{
		0: "TASK_PHASE_UNSPECIFIED",
		1: "TASK_PHASE_RUNNING",
		2: "TASK_PHASE_COMPLETED",
		3: "TASK_PHASE_FAILED",
	}
	TaskPhase_value = map[string]int32{
		"TASK_PHASE_UNSPECIFIED": 0,
		"TASK_PHASE_RUNNING":     1,
		"TASK_PHASE_COMPLETED":   2,
		"TASK_PHASE_FAILED":      3,
	}
)

func (x TaskPhase) Enum() *TaskPhase {
	p := new(TaskPhase)
	*p = x
	return p
}

func (x TaskPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (TaskPhase) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[1]
}

func (x TaskPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPhase.Descriptor instead.
func (TaskPhase) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EnrollRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type EnrollResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AgentCredential string                 `protobuf:"bytes,2,opt,name=agent_credential,json=agentCredential,proto3" json:"agent_credential,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *EnrollResponse) GetAgentCredential() string {
	if x != nil {
		return x.AgentCredential
	}
	return ""
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_DeployStatus
	//	*AgentMessage_BackupStatus
	//	*AgentMessage_RestoreStatus
	//	*AgentMessage_ContainerDetail
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetDeployStatus() *DeployStatus {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_DeployStatus); ok {
			return x.DeployStatus
		}
	}
	return nil
}

func (x *AgentMessage) GetBackupStatus() *BackupStatus {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_BackupStatus); ok {
			return x.BackupStatus
		}
	}
	return nil
}

func (x *AgentMessage) GetRestoreStatus() *RestoreStatus {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_RestoreStatus); ok {
			return x.RestoreStatus
		}
	}
	return nil
}

func (x *AgentMessage) GetContainerDetail() *ContainerDetail {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ContainerDetail); ok {
			return x.ContainerDetail
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_DeployStatus struct {
	DeployStatus *DeployStatus `protobuf:"bytes,2,opt,name=deploy_status,json=deployStatus,proto3,oneof"`
}

type AgentMessage_BackupStatus struct {
	BackupStatus *BackupStatus `protobuf:"bytes,3,opt,name=backup_status,json=backupStatus,proto3,oneof"`
}

type AgentMessage_RestoreStatus struct {
	RestoreStatus *RestoreStatus `protobuf:"bytes,4,opt,name=restore_status,json=restoreStatus,proto3,oneof"`
}

type AgentMessage_ContainerDetail struct {
	ContainerDetail *ContainerDetail `protobuf:"bytes,5,opt,name=container_detail,json=containerDetail,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_DeployStatus) isAgentMessage_Payload() {}

func (*AgentMessage_BackupStatus) isAgentMessage_Payload() {}

func (*AgentMessage_RestoreStatus) isAgentMessage_Payload() {}

func (*AgentMessage_ContainerDetail) isAgentMessage_Payload() {}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_DeployStack
	//	*ControlMessage_Ack
	//	*ControlMessage_Backup
	//	*ControlMessage_Restore
	//	*ControlMessage_InspectContainer
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetDeployStack() *DeployStackCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_DeployStack); ok {
			return x.DeployStack
		}
	}
	return nil
}

func (x *ControlMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ControlMessage) GetBackup() *BackupCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Backup); ok {
			return x.Backup
		}
	}
	return nil
}

func (x *ControlMessage) GetRestore() *RestoreCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

func (x *ControlMessage) GetInspectContainer() *InspectContainerCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_InspectContainer); ok {
			return x.InspectContainer
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_DeployStack struct {
	DeployStack *DeployStackCommand `protobuf:"bytes,1,opt,name=deploy_stack,json=deployStack,proto3,oneof"`
}

type ControlMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type ControlMessage_Backup struct {
	Backup *BackupCommand `protobuf:"bytes,3,opt,name=backup,proto3,oneof"`
}

type ControlMessage_Restore struct {
	Restore *RestoreCommand `protobuf:"bytes,4,opt,name=restore,proto3,oneof"`
}

type ControlMessage_InspectContainer struct {
	InspectContainer *InspectContainerCommand `protobuf:"bytes,5,opt,name=inspect_container,json=inspectContainer,proto3,oneof"`
}

func (*ControlMessage_DeployStack) isControlMessage_Payload() {}

func (*ControlMessage_Ack) isControlMessage_Payload() {}

func (*ControlMessage_Backup) isControlMessage_Payload() {}

func (*ControlMessage_Restore) isControlMessage_Payload() {}

func (*ControlMessage_InspectContainer) isControlMessage_Payload() {}

type Heartbeat struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ServerId   string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SentAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Resources  *ResourceSnapshot      `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	Containers []*ContainerSummary    `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	// False means "not refreshed this tick" (see edge-device tuning's
	// container-list gating), not "genuinely zero containers running" —
	// a repeated field alone can't distinguish those two cases.
	ContainersIncluded bool `protobuf:"varint,5,opt,name=containers_included,json=containersIncluded,proto3" json:"containers_included,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Heartbeat) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Heartbeat) GetResources() *ResourceSnapshot {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Heartbeat) GetContainers() []*ContainerSummary {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *Heartbeat) GetContainersIncluded() bool {
	if x != nil {
		return x.ContainersIncluded
	}
	return false
}

type ResourceSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,2,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	DiskPercent   float64                `protobuf:"fixed64,3,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSnapshot) Reset() {
	*x = ResourceSnapshot{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSnapshot) ProtoMessage() {}

func (x *ResourceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSnapshot.ProtoReflect.Descriptor instead.
func (*ResourceSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceSnapshot) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceSnapshot) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *ResourceSnapshot) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

type ContainerSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,4,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	ImageId       string                 `protobuf:"bytes,6,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	CreatedUnix   int64                  `protobuf:"varint,7,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Ports         []*ContainerPort       `protobuf:"bytes,9,rep,name=ports,proto3" json:"ports,omitempty"`
	Networks      []*ContainerNetwork    `protobuf:"bytes,10,rep,name=networks,proto3" json:"networks,omitempty"`
	Mounts        []*ContainerMount      `protobuf:"bytes,11,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSummary) Reset() {
	*x = ContainerSummary{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSummary) ProtoMessage() {}

func (x *ContainerSummary) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSummary.ProtoReflect.Descriptor instead.
func (*ContainerSummary) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerSummary) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *ContainerSummary) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerSummary) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ContainerSummary) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

func (x *ContainerSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerSummary) GetPorts() []*ContainerPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerSummary) GetNetworks() []*ContainerNetwork {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *ContainerSummary) GetMounts() []*ContainerMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type ContainerPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	PrivatePort   uint32                 `protobuf:"varint,2,opt,name=private_port,json=privatePort,proto3" json:"private_port,omitempty"`
	PublicPort    uint32                 `protobuf:"varint,3,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerPort) Reset() {
	*x = ContainerPort{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerPort) ProtoMessage() {}

func (x *ContainerPort) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerPort.ProtoReflect.Descriptor instead.
func (*ContainerPort) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerPort) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ContainerPort) GetPrivatePort() uint32 {
	if x != nil {
		return x.PrivatePort
	}
	return 0
}

func (x *ContainerPort) GetPublicPort() uint32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *ContainerPort) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ContainerNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerNetwork) Reset() {
	*x = ContainerNetwork{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerNetwork) ProtoMessage() {}

func (x *ContainerNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerNetwork.ProtoReflect.Descriptor instead.
func (*ContainerNetwork) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerNetwork) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerNetwork) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type ContainerMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	ReadWrite     bool                   `protobuf:"varint,5,opt,name=read_write,json=readWrite,proto3" json:"read_write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerMount) Reset() {
	*x = ContainerMount{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMount) ProtoMessage() {}

func (x *ContainerMount) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMount.ProtoReflect.Descriptor instead.
func (*ContainerMount) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ContainerMount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContainerMount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContainerMount) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ContainerMount) GetReadWrite() bool {
	if x != nil {
		return x.ReadWrite
	}
	return false
}

type DeployStackCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	StackName     string                 `protobuf:"bytes,2,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	ComposeYaml   string                 `protobuf:"bytes,3,opt,name=compose_yaml,json=composeYaml,proto3" json:"compose_yaml,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployStackCommand) Reset() {
	*x = DeployStackCommand{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployStackCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployStackCommand) ProtoMessage() {}

func (x *DeployStackCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployStackCommand.ProtoReflect.Descriptor instead.
func (*DeployStackCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DeployStackCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployStackCommand) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *DeployStackCommand) GetComposeYaml() string {
	if x != nil {
		return x.ComposeYaml
	}
	return ""
}

func (x *DeployStackCommand) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type DeployStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Phase         DeployPhase            `protobuf:"varint,2,opt,name=phase,proto3,enum=agent.v1.DeployPhase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployStatus) Reset() {
	*x = DeployStatus{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployStatus) ProtoMessage() {}

func (x *DeployStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployStatus.ProtoReflect.Descriptor instead.
func (*DeployStatus) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DeployStatus) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployStatus) GetPhase() DeployPhase {
	if x != nil {
		return x.Phase
	}
	return DeployPhase_DEPLOY_PHASE_UNSPECIFIED
}

func (x *DeployStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeployStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *Ack) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// BackupCommand tells the agent to snapshot every named volume belonging
// to deployment_id into a single tar stream and PUT it to upload_url.
// Bulk bytes deliberately don't travel over the AgentSession stream
// itself (see internal/controlplane/backup's doc comment) — upload_url
// is a separate authenticated HTTP endpoint so a large transfer can't
// starve heartbeats/other commands sharing this stream's one outbound
// channel.
type BackupCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupId      string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,3,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCommand) Reset() {
	*x = BackupCommand{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCommand) ProtoMessage() {}

func (x *BackupCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCommand.ProtoReflect.Descriptor instead.
func (*BackupCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *BackupCommand) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *BackupCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *BackupCommand) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

type BackupStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupId      string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	Phase         TaskPhase              `protobuf:"varint,2,opt,name=phase,proto3,enum=agent.v1.TaskPhase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupStatus) Reset() {
	*x = BackupStatus{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStatus) ProtoMessage() {}

func (x *BackupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStatus.ProtoReflect.Descriptor instead.
func (*BackupStatus) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *BackupStatus) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *BackupStatus) GetPhase() TaskPhase {
	if x != nil {
		return x.Phase
	}
	return TaskPhase_TASK_PHASE_UNSPECIFIED
}

func (x *BackupStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BackupStatus) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// RestoreCommand tells the agent to GET a tar snapshot from download_url,
// extract it back into deployment_id's named volumes, then redeploy
// (stack_name/compose_yaml/env are included because the agent doesn't
// cache the original DeployStackCommand — this is what makes restore
// bring the containers back up on top of the restored data rather than
// just leaving the volumes populated with nothing running).
type RestoreCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupId      string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,3,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	StackName     string                 `protobuf:"bytes,4,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	ComposeYaml   string                 `protobuf:"bytes,5,opt,name=compose_yaml,json=composeYaml,proto3" json:"compose_yaml,omitempty"`
	Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreCommand) Reset() {
	*x = RestoreCommand{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCommand) ProtoMessage() {}

func (x *RestoreCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCommand.ProtoReflect.Descriptor instead.
func (*RestoreCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *RestoreCommand) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *RestoreCommand) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *RestoreCommand) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *RestoreCommand) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *RestoreCommand) GetComposeYaml() string {
	if x != nil {
		return x.ComposeYaml
	}
	return ""
}

func (x *RestoreCommand) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// RestoreStatus covers only the download+extract step. Once that
// completes, the agent immediately re-runs the normal deploy pipeline
// (internal/agent/docker.Deploy) on top of the restored volumes, which
// reports its own DeployStatus events through the existing path — so a
// restore's "containers coming back up" progress reuses deployment_events
// rather than this message needing to duplicate it.
type RestoreStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupId      string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Phase         TaskPhase              `protobuf:"varint,3,opt,name=phase,proto3,enum=agent.v1.TaskPhase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreStatus) Reset() {
	*x = RestoreStatus{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStatus) ProtoMessage() {}

func (x *RestoreStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStatus.ProtoReflect.Descriptor instead.
func (*RestoreStatus) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *RestoreStatus) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *RestoreStatus) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *RestoreStatus) GetPhase() TaskPhase {
	if x != nil {
		return x.Phase
	}
	return TaskPhase_TASK_PHASE_UNSPECIFIED
}

func (x *RestoreStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// InspectContainerCommand asks the agent to run a live ContainerInspect for
// one container and reply with ContainerDetail carrying request_id
// unchanged, so the control plane can correlate the async reply back to
// the HTTP request that triggered it. Deliberately not part of the
// heartbeat: ContainerInspect is a per-container round-trip, too expensive
// to run for every container on every heartbeat tick across a fleet, so
// it's only issued on demand when a user opens a container's detail view.
type InspectContainerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectContainerCommand) Reset() {
	*x = InspectContainerCommand{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectContainerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectContainerCommand) ProtoMessage() {}

func (x *InspectContainerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectContainerCommand.ProtoReflect.Descriptor instead.
func (*InspectContainerCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *InspectContainerCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InspectContainerCommand) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *InspectContainerCommand) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type ContainerDetail struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	RequestId                  string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ContainerId                string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Found                      bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	ErrorMessage               string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Env                        []string               `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	RestartPolicyName          string                 `protobuf:"bytes,6,opt,name=restart_policy_name,json=restartPolicyName,proto3" json:"restart_policy_name,omitempty"`
	RestartPolicyMaxRetryCount int32                  `protobuf:"varint,7,opt,name=restart_policy_max_retry_count,json=restartPolicyMaxRetryCount,proto3" json:"restart_policy_max_retry_count,omitempty"`
	HealthStatus               string                 `protobuf:"bytes,8,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	HealthFailingStreak        int32                  `protobuf:"varint,9,opt,name=health_failing_streak,json=healthFailingStreak,proto3" json:"health_failing_streak,omitempty"`
	RestartCount               int32                  `protobuf:"varint,10,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ContainerDetail) Reset() {
	*x = ContainerDetail{}
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerDetail) ProtoMessage() {}

func (x *ContainerDetail) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerDetail.ProtoReflect.Descriptor instead.
func (*ContainerDetail) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ContainerDetail) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ContainerDetail) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerDetail) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ContainerDetail) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ContainerDetail) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerDetail) GetRestartPolicyName() string {
	if x != nil {
		return x.RestartPolicyName
	}
	return ""
}

func (x *ContainerDetail) GetRestartPolicyMaxRetryCount() int32 {
	if x != nil {
		return x.RestartPolicyMaxRetryCount
	}
	return 0
}

func (x *ContainerDetail) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *ContainerDetail) GetHealthFailingStreak() int32 {
	if x != nil {
		return x.HealthFailingStreak
	}
	return 0
}

func (x *ContainerDetail) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\"X\n" +
	"\x0eEnrollResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12)\n" +
	"\x10agent_credential\x18\x02 \x01(\tR\x0fagentCredential\"\xd6\x02\n" +
	"\fAgentMessage\x123\n" +
	"\theartbeat\x18\x01 \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\rdeploy_status\x18\x02 \x01(\v2\x16.agent.v1.DeployStatusH\x00R\fdeployStatus\x12=\n" +
	"\rbackup_status\x18\x03 \x01(\v2\x16.agent.v1.BackupStatusH\x00R\fbackupStatus\x12@\n" +
	"\x0erestore_status\x18\x04 \x01(\v2\x17.agent.v1.RestoreStatusH\x00R\rrestoreStatus\x12F\n" +
	"\x10container_detail\x18\x05 \x01(\v2\x19.agent.v1.ContainerDetailH\x00R\x0fcontainerDetailB\t\n" +
	"\apayload\"\xbc\x02\n" +
	"\x0eControlMessage\x12A\n" +
	"\fdeploy_stack\x18\x01 \x01(\v2\x1c.agent.v1.DeployStackCommandH\x00R\vdeployStack\x12!\n" +
	"\x03ack\x18\x02 \x01(\v2\r.agent.v1.AckH\x00R\x03ack\x121\n" +
	"\x06backup\x18\x03 \x01(\v2\x17.agent.v1.BackupCommandH\x00R\x06backup\x124\n" +
	"\arestore\x18\x04 \x01(\v2\x18.agent.v1.RestoreCommandH\x00R\arestore\x12P\n" +
	"\x11inspect_container\x18\x05 \x01(\v2!.agent.v1.InspectContainerCommandH\x00R\x10inspectContainerB\t\n" +
	"\apayload\"\x84\x02\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x128\n" +
	"\tresources\x18\x03 \x01(\v2\x1a.agent.v1.ResourceSnapshotR\tresources\x12:\n" +
	"\n" +
	"containers\x18\x04 \x03(\v2\x1a.agent.v1.ContainerSummaryR\n" +
	"containers\x12/\n" +
	"\x13containers_included\x18\x05 \x01(\bR\x12containersIncluded\"w\n" +
	"\x10ResourceSnapshot\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x02 \x01(\x01R\n" +
	"memPercent\x12!\n" +
	"\fdisk_percent\x18\x03 \x01(\x01R\vdiskPercent\"\xf6\x02\n" +
	"\x10ContainerSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12#\n" +
	"\rdeployment_id\x18\x04 \x01(\tR\fdeploymentId\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x19\n" +
	"\bimage_id\x18\x06 \x01(\tR\aimageId\x12!\n" +
	"\fcreated_unix\x18\a \x01(\x03R\vcreatedUnix\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12-\n" +
	"\x05ports\x18\t \x03(\v2\x17.agent.v1.ContainerPortR\x05ports\x126\n" +
	"\bnetworks\x18\n" +
	" \x03(\v2\x1a.agent.v1.ContainerNetworkR\bnetworks\x120\n" +
	"\x06mounts\x18\v \x03(\v2\x18.agent.v1.ContainerMountR\x06mounts\"w\n" +
	"\rContainerPort\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12!\n" +
	"\fprivate_port\x18\x02 \x01(\rR\vprivatePort\x12\x1f\n" +
	"\vpublic_port\x18\x03 \x01(\rR\n" +
	"publicPort\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"E\n" +
	"\x10ContainerNetwork\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\"\x91\x01\n" +
	"\x0eContainerMount\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12\x1d\n" +
	"\n" +
	"read_write\x18\x05 \x01(\bR\treadWrite\"\xec\x01\n" +
	"\x12DeployStackCommand\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18\x02 \x01(\tR\tstackName\x12!\n" +
	"\fcompose_yaml\x18\x03 \x01(\tR\vcomposeYaml\x127\n" +
	"\x03env\x18\x04 \x03(\v2%.agent.v1.DeployStackCommand.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x01\n" +
	"\fDeployStatus\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12+\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x15.agent.v1.DeployPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"$\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"p\n" +
	"\rBackupCommand\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x03 \x01(\tR\tuploadUrl\"\x8f\x01\n" +
	"\fBackupStatus\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12)\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x13.agent.v1.TaskPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"\xa4\x02\n" +
	"\x0eRestoreCommand\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12!\n" +
	"\fdownload_url\x18\x03 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"stack_name\x18\x04 \x01(\tR\tstackName\x12!\n" +
	"\fcompose_yaml\x18\x05 \x01(\tR\vcomposeYaml\x123\n" +
	"\x03env\x18\x06 \x03(\v2!.agent.v1.RestoreCommand.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\rRestoreStatus\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12)\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x13.agent.v1.TaskPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"x\n" +
	"\x17InspectContainerCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\"\x92\x03\n" +
	"\x0fContainerDetail\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x10\n" +
	"\x03env\x18\x05 \x03(\tR\x03env\x12.\n" +
	"\x13restart_policy_name\x18\x06 \x01(\tR\x11restartPolicyName\x12B\n" +
	"\x1erestart_policy_max_retry_count\x18\a \x01(\x05R\x1arestartPolicyMaxRetryCount\x12#\n" +
	"\rhealth_status\x18\b \x01(\tR\fhealthStatus\x122\n" +
	"\x15health_failing_streak\x18\t \x01(\x05R\x13healthFailingStreak\x12#\n" +
	"\rrestart_count\x18\n" +
	" \x01(\x05R\frestartCount*\xad\x01\n" +
	"\vDeployPhase\x12\x1c\n" +
	"\x18DEPLOY_PHASE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DEPLOY_PHASE_PENDING\x10\x01\x12\x18\n" +
	"\x14DEPLOY_PHASE_PULLING\x10\x02\x12\x19\n" +
	"\x15DEPLOY_PHASE_CREATING\x10\x03\x12\x18\n" +
	"\x14DEPLOY_PHASE_RUNNING\x10\x04\x12\x17\n" +
	"\x13DEPLOY_PHASE_FAILED\x10\x05*p\n" +
	"\tTaskPhase\x12\x1a\n" +
	"\x16TASK_PHASE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_PHASE_RUNNING\x10\x01\x12\x18\n" +
	"\x14TASK_PHASE_COMPLETED\x10\x02\x12\x15\n" +
	"\x11TASK_PHASE_FAILED\x10\x032\x8c\x01\n" +
	"\fAgentSession\x12;\n" +
	"\x06Enroll\x12\x17.agent.v1.EnrollRequest\x1a\x18.agent.v1.EnrollResponse\x12?\n" +
	"\aSession\x12\x16.agent.v1.AgentMessage\x1a\x18.agent.v1.ControlMessage(\x010\x01BGZEgithub.com/ankitapaul1586-cmd/pspocketedge/internal/shared/pb/agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_agent_v1_agent_proto_goTypes = []any{
	(DeployPhase)(0),                // 0: agent.v1.DeployPhase
	(TaskPhase)(0),                  // 1: agent.v1.TaskPhase
	(*EnrollRequest)(nil),           // 2: agent.v1.EnrollRequest
	(*EnrollResponse)(nil),          // 3: agent.v1.EnrollResponse
	(*AgentMessage)(nil),            // 4: agent.v1.AgentMessage
	(*ControlMessage)(nil),          // 5: agent.v1.ControlMessage
	(*Heartbeat)(nil),               // 6: agent.v1.Heartbeat
	(*ResourceSnapshot)(nil),        // 7: agent.v1.ResourceSnapshot
	(*ContainerSummary)(nil),        // 8: agent.v1.ContainerSummary
	(*ContainerPort)(nil),           // 9: agent.v1.ContainerPort
	(*ContainerNetwork)(nil),        // 10: agent.v1.ContainerNetwork
	(*ContainerMount)(nil),          // 11: agent.v1.ContainerMount
	(*DeployStackCommand)(nil),      // 12: agent.v1.DeployStackCommand
	(*DeployStatus)(nil),            // 13: agent.v1.DeployStatus
	(*Ack)(nil),                     // 14: agent.v1.Ack
	(*BackupCommand)(nil),           // 15: agent.v1.BackupCommand
	(*BackupStatus)(nil),            // 16: agent.v1.BackupStatus
	(*RestoreCommand)(nil),          // 17: agent.v1.RestoreCommand
	(*RestoreStatus)(nil),           // 18: agent.v1.RestoreStatus
	(*InspectContainerCommand)(nil), // 19: agent.v1.InspectContainerCommand
	(*ContainerDetail)(nil),         // 20: agent.v1.ContainerDetail
	nil,                             // 21: agent.v1.DeployStackCommand.EnvEntry
	nil,                             // 22: agent.v1.RestoreCommand.EnvEntry
	(*timestamppb.Timestamp)(nil),   // 23: google.protobuf.Timestamp
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	6,  // 0: agent.v1.AgentMessage.heartbeat:type_name -> agent.v1.Heartbeat
	13, // 1: agent.v1.AgentMessage.deploy_status:type_name -> agent.v1.DeployStatus
	16, // 2: agent.v1.AgentMessage.backup_status:type_name -> agent.v1.BackupStatus
	18, // 3: agent.v1.AgentMessage.restore_status:type_name -> agent.v1.RestoreStatus
	20, // 4: agent.v1.AgentMessage.container_detail:type_name -> agent.v1.ContainerDetail
	12, // 5: agent.v1.ControlMessage.deploy_stack:type_name -> agent.v1.DeployStackCommand
	14, // 6: agent.v1.ControlMessage.ack:type_name -> agent.v1.Ack
	15, // 7: agent.v1.ControlMessage.backup:type_name -> agent.v1.BackupCommand
	17, // 8: agent.v1.ControlMessage.restore:type_name -> agent.v1.RestoreCommand
	19, // 9: agent.v1.ControlMessage.inspect_container:type_name -> agent.v1.InspectContainerCommand
	23, // 10: agent.v1.Heartbeat.sent_at:type_name -> google.protobuf.Timestamp
	7,  // 11: agent.v1.Heartbeat.resources:type_name -> agent.v1.ResourceSnapshot
	8,  // 12: agent.v1.Heartbeat.containers:type_name -> agent.v1.ContainerSummary
	9,  // 13: agent.v1.ContainerSummary.ports:type_name -> agent.v1.ContainerPort
	10, // 14: agent.v1.ContainerSummary.networks:type_name -> agent.v1.ContainerNetwork
	11, // 15: agent.v1.ContainerSummary.mounts:type_name -> agent.v1.ContainerMount
	21, // 16: agent.v1.DeployStackCommand.env:type_name -> agent.v1.DeployStackCommand.EnvEntry
	0,  // 17: agent.v1.DeployStatus.phase:type_name -> agent.v1.DeployPhase
	23, // 18: agent.v1.DeployStatus.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 19: agent.v1.BackupStatus.phase:type_name -> agent.v1.TaskPhase
	22, // 20: agent.v1.RestoreCommand.env:type_name -> agent.v1.RestoreCommand.EnvEntry
	1,  // 21: agent.v1.RestoreStatus.phase:type_name -> agent.v1.TaskPhase
	2,  // 22: agent.v1.AgentSession.Enroll:input_type -> agent.v1.EnrollRequest
	4,  // 23: agent.v1.AgentSession.Session:input_type -> agent.v1.AgentMessage
	3,  // 24: agent.v1.AgentSession.Enroll:output_type -> agent.v1.EnrollResponse
	5,  // 25: agent.v1.AgentSession.Session:output_type -> agent.v1.ControlMessage
	24, // [24:26] is the sub-list for method output_type
	22, // [22:24] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_DeployStatus)(nil),
		(*AgentMessage_BackupStatus)(nil),
		(*AgentMessage_RestoreStatus)(nil),
		(*AgentMessage_ContainerDetail)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*ControlMessage_DeployStack)(nil),
		(*ControlMessage_Ack)(nil),
		(*ControlMessage_Backup)(nil),
		(*ControlMessage_Restore)(nil),
		(*ControlMessage_InspectContainer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
