package dbcatalog

import (
	"errors"
	"time"
)

// CommandContext is what an in-container command needs to know. Every
// value in it is either chosen from validated identifiers (usernames,
// database names) or generated by vault.GeneratePassword (alphanumeric),
// so interpolating it into SQL string literals is safe — the argv itself
// is never passed through a shell except where a command says so, and
// then only as positional parameters ("$1"), never spliced into the
// script.
type CommandContext struct {
	Username string
	Database string
	// Password is the admin password currently in effect; NewPassword is
	// only set for a rotation.
	Password    string
	NewPassword string
	// Token is the engine's extra admin token, when it has one
	// (InfluxDB).
	Token string
}

// commandSet is an engine's operations on a running instance. Nil
// functions mean unsupported.
type commandSet struct {
	// reservedUsernames can't be chosen as the admin username (they
	// already exist with different semantics, e.g. MongoDB's
	// "__system").
	reservedUsernames []string
	// reservedPrefix, if set, can't start the admin username (PostgreSQL
	// reserves "pg_").
	reservedPrefix string
	rotate         func(c CommandContext) []string
	createTemp     func(c CommandContext, user, password string, expires time.Time) []string
	dropTemp       func(c CommandContext, user string) []string
}

// ErrUnsupported is returned for an operation an engine doesn't offer.
var ErrUnsupported = errors.New("not supported for this engine")

// RotateCommand returns the argv that changes the admin password in a
// running instance. Only meaningful for RotationExec engines.
func (e *Engine) RotateCommand(c CommandContext) ([]string, error) {
	if e.Rotation != RotationExec || e.commands == nil || e.commands.rotate == nil {
		return nil, ErrUnsupported
	}
	return e.commands.rotate(c), nil
}

// CreateTemporaryUserCommand returns the argv that creates a read-only
// login that the database itself expires where it can (PostgreSQL VALID
// UNTIL); the scheduler also drops it at expiry regardless.
func (e *Engine) CreateTemporaryUserCommand(c CommandContext, user, password string, expires time.Time) ([]string, error) {
	if !e.TemporaryUsers || e.commands == nil || e.commands.createTemp == nil {
		return nil, ErrUnsupported
	}
	if !identifierRE.MatchString(user) {
		return nil, errors.New("invalid temporary username")
	}
	return e.commands.createTemp(c, user, password, expires), nil
}

// DropTemporaryUserCommand returns the argv that removes a temporary
// login and ends its sessions.
func (e *Engine) DropTemporaryUserCommand(c CommandContext, user string) ([]string, error) {
	if !e.TemporaryUsers || e.commands == nil || e.commands.dropTemp == nil {
		return nil, ErrUnsupported
	}
	if !identifierRE.MatchString(user) {
		return nil, errors.New("invalid temporary username")
	}
	return e.commands.dropTemp(c, user), nil
}
